### ISSUE TITLE
Make a DOI and add it to the citation.cff file

### ISSUE THREAD

**Issue by kaijagahm** [kaijagahm/R-help-reprexes#29]
How to: https://the-turing-way.netlify.app/communication/citable/citable-steps.html?highlight=doi#dois

**Comment by xortizross** [comment]
It seems that DOIs in the carpentries are issues by zenodo, I think that's where stuff gets uploaded, maybe we will get one once the lesson is officially in the incubator?

**Comment by xortizross** [comment]
Clearly I wasn't paying close attention during this section of the training, but I now see that it is probably up to us to generate a DOI. The lesson development training uses zonodo (https://zenodo.org/records/8410626), I have used OSF as a repo for my research data. I am happy to go ahead and create a project or some other object in either. I am not familiar with Zenodo but we could even create a whole project with OSF with different components (I am thinking for you Kaija, you can then link TAR methods, analyses, data, etc.). However, DOIs in Zenodo are numbers, while OSF has letters lol

Update: I wanted to play around so just created a (currently private) [project in OSF](https://osf.io/37jpq/?view_only=0a048d28f6854113bbcf153cf395de20), so if we decide to keep it we have a doi! OSF can also be linked to a GitHub repo:
<img width="582" alt="image" src="https://github.com/user-attachments/assets/b878579c-f4d7-43d9-b6ab-e373e5690734">

**Comment by xortizross** [comment]
Kaija and I agreed to open the project on OSF, all developers were added as contributors (@peterlaurin you should get an email to register). It is now public and here is the DOI: 10.17605/OSF.IO/37JPQ
