### ISSUE TITLE
Ask people to join pre-alpha lesson demo (Aug 12/13)

### ISSUE THREAD

**Issue by peterlaurin** [kaijagahm/R-help-reprexes#8]
Peter: Mariana (Garud Lab), Madigan
Kaija: Maddie 
Xochitl: Taylor

**Comment by peterlaurin** [comment]
Attendees: 
@xortizross @peterlaurin @kaijagahm 
Taylor (TBD)
Evan Doughty (probably)
Emily (TBD)
Madigan Durham
Maddie (TBD)
Garrett 
Mariana Harris

**Comment by kaijagahm** [comment]
Attendees:
@xortizross @peterlaurin @kaijagahm
Evan Doughty (probably)
Emily (TBD)
Madigan Durham
Maddie
Garrett
Mariana Harris

**Comment by peterlaurin** [comment]
Send the final date (Aug 12) to people

**Comment by kaijagahm** [comment]
Lesson demo completed
